# Generated by Django 5.0.4 on 2024-11-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex10', '0002_alter_planets_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
